name: Build and Push Multi-Arch Docker Image

on:
  # 1. Manual trigger
  workflow_dispatch: 
    inputs:
      tag:
        description: 'Tag/Version to build (e.g., v0.107.70)'
        required: true
        default: 'latest'

  # 2. External API trigger
  repository_dispatch:
    types: [new_adguardhome_release]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up QEMU (for ARM64 emulation)
        uses: actions/docker-setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: actions/docker-setup-buildx-action@v3

      # --- AJOUT CRUCIAL POUR LE HARDENED ---
      - name: Login to dhi.io (Hardened Images)
        uses: docker/login-action@v3
        with:
          registry: dhi.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Login to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # Build and push the multi-arch image
      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        
        # On définit la valeur du TAG pour l'utiliser dans les étapes suivantes
        env:
          TAG_VALUE: ${{ github.event.client_payload.tag_name || github.event.inputs.tag || 'latest' }}
        
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          # Utilisation du cache GHA pour la vitesse
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
          build-args: |
            AGH_VERSION=${{ env.TAG_VALUE }}
            
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/adguardhome-unbound-redis:${{ env.TAG_VALUE }}
            ghcr.io/imthai/adguardhome-unbound-redis:${{ env.TAG_VALUE }}
            ${{ secrets.DOCKERHUB_USERNAME }}/adguardhome-unbound-redis:latest
            ghcr.io/imthai/adguardhome-unbound-redis:latest
